# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Spenza"
client_id = "ebec36c2020ab9d34476917642e2d645"
application_url = "https://dd60-122-180-175-93.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_orders,read_product_listings,read_customers"

[auth]
redirect_urls = [
  "https://dd60-122-180-175-93.ngrok-free.app/auth/callback",
  "https://dd60-122-180-175-93.ngrok-free.app/auth/shopify/callback",
  "https://dd60-122-180-175-93.ngrok-free.app/api/auth/callback",
  "https://dd60-122-180-175-93.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "isimplexity.myshopify.com"
