# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "spenza-app"
client_id = "e7ad83db6087a33e2ffdc9c96af0f854"
application_url = "https://85a3-182-64-202-95.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = [
  "https://85a3-182-64-202-95.ngrok-free.app/auth/callback",
  "https://85a3-182-64-202-95.ngrok-free.app/auth/shopify/callback",
  "https://85a3-182-64-202-95.ngrok-free.app/api/auth/callback",
  "https://85a3-182-64-202-95.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "spenzastore.myshopify.com"
